/**
 * Repository functions for the robots table.
 *
 * Every function takes a `db` instance as its first argument so that
 * callers can inject an in-memory database during tests.
 */

/**
 * Bulk-inserts robots for a simulation, all starting at position (0, 0).
 *
 * Each robot is assigned a turn_order equal to its index in the
 * robotNames array (0-based).
 *
 * @param {import('better-sqlite3').Database} db
 * @param {number} simulationId
 * @param {string[]} robotNames - Names generated by assignRobotNames()
 * @returns {void}
 */
export function createRobots(db, simulationId, robotNames) {
  const insert = db.prepare(
    `INSERT INTO robots (simulation_id, name, position_x, position_y, turn_order)
     VALUES (?, ?, 0, 0, ?)`
  );

  const insertAll = db.transaction((names) => {
    for (let i = 0; i < names.length; i++) {
      insert.run(simulationId, names[i], i);
    }
  });

  insertAll(robotNames);
}

/**
 * Returns all robots for a simulation, ordered by turn_order.
 *
 * @param {import('better-sqlite3').Database} db
 * @param {number} simulationId
 * @returns {Array<{ id: number, simulation_id: number, name: string, position_x: number, position_y: number, turn_order: number }>}
 */
export function getRobotsBySimulation(db, simulationId) {
  return db
    .prepare('SELECT * FROM robots WHERE simulation_id = ? ORDER BY turn_order')
    .all(simulationId);
}

/**
 * Returns a single robot by simulation and turn order, or null if not found.
 *
 * @param {import('better-sqlite3').Database} db
 * @param {number} simulationId
 * @param {number} turnOrder
 * @returns {{ id: number, simulation_id: number, name: string, position_x: number, position_y: number, turn_order: number } | null}
 */
export function getRobotByTurnOrder(db, simulationId, turnOrder) {
  return (
    db
      .prepare('SELECT * FROM robots WHERE simulation_id = ? AND turn_order = ?')
      .get(simulationId, turnOrder) ?? null
  );
}

/**
 * Updates a robot's position.
 *
 * @param {import('better-sqlite3').Database} db
 * @param {number} robotId
 * @param {number} x
 * @param {number} y
 * @returns {number} Number of rows changed (1 on success)
 * @throws {Error} If no robot exists with the given ID
 */
export function updateRobotPosition(db, robotId, x, y) {
  const result = db
    .prepare('UPDATE robots SET position_x = ?, position_y = ? WHERE id = ?')
    .run(x, y, robotId);

  if (result.changes === 0) {
    throw new Error(`No robot found with id ${robotId}`);
  }
  return result.changes;
}

/**
 * Counts robots currently at a given position within a simulation.
 *
 * This is called BEFORE the active robot is moved, so count > 0 means
 * another robot is occupying the destination and delivery is blocked.
 *
 * @param {import('better-sqlite3').Database} db
 * @param {number} simulationId
 * @param {number} x
 * @param {number} y
 * @returns {number}
 */
export function countRobotsAtPosition(db, simulationId, x, y) {
  const row = db
    .prepare(
      `SELECT COUNT(*) AS count FROM robots
       WHERE simulation_id = ? AND position_x = ? AND position_y = ?`
    )
    .get(simulationId, x, y);
  return row.count;
}
